name: Add comments

on:
  issues:
    types:
      - labeled
  workflow_dispatch:

jobs:
  add-comment:
    if: github.event.label.name == 'Stale'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add assignee and author tags to issue comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "This issue has been labeled with ${{github.event.label.name}} by @${{github.event.sender.login}}. Assignee is @${{github.event.issue.assignee.login}} and author is @${{github.event.issue.user.login}}."

